### ISSUE TITLE
Landfall patch - READ THIS!

### ISSUE THREAD

**Issue by cybrann** [cooler-SAI/JadeCore548-patched#13]
@cooler-SAI  @Joslyn-Maddie 
Does any of you know how to add the building that were introduce in 5.1 patch Landfall. The ones we need are Operation: Shieldwall and Dominance Offensive. I will start working on legendary quest to fix all the bugs that are currently present there but without these I cannot continiue.

**Comment by cooler-SAI** [comment]
hmm..don't know, now working on fix DB start Log errors

**Comment by cybrann** [comment]
Ok, if someone knows it should be done asap. Also I'm starting to work now on primordius and galakras scripts.
