### ISSUE TITLE
Command crash

### ISSUE THREAD

**Issue by justdothings** [cooler-SAI/JadeCore548-patched#17]
i cant compile with debug on linux i tried on  windows and here is crash log.

[_worldserver.exe_[31-8_15-49-49].txt](https://github.com/cooler-SAI/JadeCore548-patched/files/447111/_worldserver.exe_.31-8_15-49-49.txt)

**Comment by cybrann** [comment]
What command causes crash?

**Comment by justdothings** [comment]
any command, i think in world db missing commands cas it when i type it says command not found and than crash

**Comment by cybrann** [comment]
Never happened to me. Your core or db god corrupted
