### ISSUE TITLE
[Low priority] Item Upgrade 4 lvls

### ISSUE THREAD

**Issue by wlasser** [cooler-SAI/JadeCore548-patched#19]
There is currently have 2/2 as max and have many problems with save it values or something. I dont have many info - but it present.
On patch 5.4.8 - this is changed to 4 lvl of upgrades.
Researching on core about "item upgrade" - gave some info about that system, but related .dbc (or .db2 - don't remember) - don't have upgrade entry for that.
Need to get 5.4.8 dbc and look over it.

Thanks for all work!

**Comment by cybrann** [comment]
This is 5.4.7 18019 version, not sure why it says 5.4.8 in the repository name.

/closing since it's invalid report
