### ISSUE TITLE
DBC Bad loading

### ISSUE THREAD

**Issue by Dokman** [cooler-SAI/JadeCore548-patched#2]
So...
![image](https://cloud.githubusercontent.com/assets/2290904/13961184/c97bc6ca-f05b-11e5-8968-65db11e4fe52.png)

**Comment by Eryck73** [comment]
any help with error?

**Comment by Telence** [comment]
the dbc you're using this outdated.
download these maps mega:#!gR1RhKTD!FiI0uutDKPpP3H4Otn4-wTvGmAf83-aSMY8gNfVgF_U
