### ISSUE TITLE
Error DBC

### ISSUE THREAD

**Issue by Dev-zeros** [cooler-SAI/JadeCore548-patched#20]
Realm running as realm ID 3
Using World DB: JadeCoreDB 548.01 updates & "patch" SmartAI Lab 434.11 "Molten Front"
Will clear `logs` table of entries older than 1209600 seconds every 10 minutes.
Using DataDir ./
VMap support included. LineOfSight:1, getHeight:1, indoorCheck:1 PetLOS:1
VMap data directory is: ./vmaps
Loading Trinity strings...
>> Loaded 1100 Trinity strings from table trinity_string in 2 ms
Initialize data stores...
Some required *.dbc files (2 from 142) not found or not compatible:
./dbc/BattlemasterList.dbc (exists, but has 20 fields instead of 30) Possible wrong client version.
./dbc/LFGDungeons.dbc (exists, but has 21 fields instead of 29) Possible wrong client version.

root@wow-bolivia:/home/wow/MOP/bin#

uso DBC get dbc_maps_vmaps_mmaps.txt y mapextractor compilado y arroja error espero pronta repsuesta

**Comment by cooler-SAI** [comment]
all works good for me from dbc_maps_vmaps_mmaps.txt link download, so, closed
