### ISSUE TITLE
Server-Crash (Worgen)

### ISSUE THREAD

**Issue by Mysterium** [cooler-SAI/JadeCore548-patched#24]
Hey,

the server crashed, when you make the first quest in the worgen start

Log:

World initialized in 0 minutes 33 seconds
worldserver process priority class set to HIGH
Starting up anti-freeze thread (30 seconds max stuck time)...
Starting Trinity RA on port 3443 on 0.0.0.0
JadeCore rev.  () (Win32, Release) (worldserver-daemon) ready...
Spell action 88161 not added into button 73 for player Testworgen: spell not exist
DoScriptText with source entry 34850 (TypeId=3, guid=996261) could not find text entry -1638000.
DoScriptText with source entry 34850 (TypeId=3, guid=996261) could not find text entry -1638001.
DoScriptText with source entry 34981 (TypeId=3, guid=970408) could not find text entry -1638003.
DoScriptText with source entry 34913 (TypeId=3, guid=998448) could not find text entry -1638028.

Maybe the DoScriptText causes the crash

**Comment by cybrann** [comment]
Worgen zone is not scripted yet. I think the worgens are set to start in northshire same as humans.

**Comment by cooler-SAI** [comment]
or I can place portal to stormwind

**Comment by cybrann** [comment]
Closing this until worgen start zone is fixed. Then we will accept issues about worgen start zone.
