### ISSUE TITLE
spell don't work

### ISSUE THREAD

**Issue by a7244869** [cooler-SAI/JadeCore548-patched#26]
Boss:Jin'rokh   
 Raid: Throne of Thunder

I give spell(137180) add script in database  but this spell is no effect (no damage and no coma effect) spell(137161) spell(137167) Also added a script in database.

And I give spell (137162) add script in database but this spell is no effect(After the time disappeared 
 No trigger 10 stacks debuff(138349))     spell(138349) add a script in database

**Comment by cybrann** [comment]
If you have just read commits you would notice that Jin'rokh script is in phase of rewritting thus it is still not finished.

/Closing issue report
