### ISSUE TITLE
error linux

### ISSUE THREAD

**Issue by warlokowla** [cooler-SAI/JadeCore548-patched#3]
../game/libgame.a(Channel.cpp.o): In function `Channel::Say(unsigned long, char const*, unsigned int)':
Channel.cpp.text+0x62ec): undefined reference to `Player::BuildPlayerChat(WorldPacket*, unsigned char, std::strin g const&, unsigned int, char const*, std::string const&) const'
collect2: error: ld returned 1 exit status
src/server/worldserver/CMakeFiles/worldserver.dir/build.make:250: recipe for target 'src/server/worldserver/worldse rver' failed
make[2]: *** [src/server/worldserver/worldserver] Error 1
CMakeFiles/Makefile2:960: recipe for target 'src/server/worldserver/CMakeFiles/worldserver.dir/all' failed
make[1]: *** [src/server/worldserver/CMakeFiles/worldserver.dir/all] Error 2
Makefile:117: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by angelsss** [comment]
the same error ,Have you resolve ?

**Comment by justdothings** [comment]
Same for me

**Comment by justdothings** [comment]
@cooler-sai

**Comment by Dev-zeros** [comment]
2 options
1: removes inline function
inline void Player :: BuildPlayerChat ( WorldPacket * data , uint8 msgtype , const std :: string & text , uint32 language , const char * addonPrefix / * = NULL * / , const std :: string & channel / * = "" * / ) const
in player.cpp or apply
 inline function in BuildPlayerChat ( WorldPacket * data , uint8 msgtype , const std :: string & text , uint32 language , const char * addonPrefix / * = NULL * / , const std :: string & channel / * = "" * / ) const in player.h , the function is not declared therefore that error occurs

player.cpp 
in the line 22912 
- void Player::BuildPlayerChat(WorldPacket* data, uint8 msgtype, std::string const& text, uint32 language, const char* addonPrefix /*= NULL*/, const std::string& channel /*= ""*/) const
+ void Player::BuildPlayerChat(WorldPacket* data, uint8 msgtype, std::string const& text, uint32 language, const char* addonPrefix /*= NULL*/, const std::string& channel /*= ""*/) const

**Comment by cybrann** [comment]
Closing this as we have no one who works on linux.
