### ISSUE TITLE
Dev Team

### ISSUE THREAD

**Issue by alexkulya** [cooler-SAI/JadeCore548-patched#34]
(EN) Is it possible to join your team?
(RU) Есть ли возможность присоединиться к вашей команде?

**Comment by cybrann** [comment]
@cooler-SAI When he is online he will add you

**Comment by cooler-SAI** [comment]
Welcome! :) https://github.com/cooler-SAI/JadeCore548-patched/invitations
Добро пожаловать!

**Comment by cybrann** [comment]
Now get your first commit done :D :D @alexkulya
