### ISSUE TITLE
Need help

### ISSUE THREAD

**Issue by cybrann** [cooler-SAI/JadeCore548-patched#35]
@cooler-SAI @alexkulya @Mysterium @Joslyn-Maddie 

Can any of you explain me this. While I was trying to script General Nazgrim he gains rage from some of his abilities, but I have problem with this. Now it is not problem to script some spells to give rage, but I have the problem with the amount of the rage to give. For example:

```
void ModifyRage(Unit* me,uint32 p_BaseValue, uint64 nazgrimGuid)
{
    if (nazgrimGuid == NULL)
        return;

    if (Unit* generalNazgrim = sObjectAccessor->GetCreature(*me, nazgrimGuid))
    {
        uint32 power = generalNazgrim->GetPower(Powers(POWER_RAGE));

		generalNazgrim->SetPower(Powers(POWER_RAGE), power + p_BaseValue);
    }
} // that is the custom function I made for adding rage

ModifyRage(me, 5, me->GetGUID());
```

So that function should give 5 rage but instead it gives only 2 rage. Now can someone help me figure this out or else I wont be able to finish General Nazgrim script because of this problem

**Comment by alexkulya** [comment]
You can try over - ModifyPower
me->ModifyPower(POWER_RAGE, +5);

**Comment by cybrann** [comment]
It still gives the same results :(
And now I will have problems checking amounts of the rage for his rage phase spells... Ah well I guess I'll script everything except rage gain and I'll leave that for another time
