### ISSUE TITLE
iron juggermaut & dark shaman bugs

### ISSUE THREAD

**Issue by Sxzander** [cooler-SAI/JadeCore548-patched#37]
If iron is juggermaut in the next phase is he not more attackable and runs out of the map

the dark shaman conjuring her totem permanently.

immerseus it is not divided when he is on 1 hp of the battle is over and he will summon the lootbare box

norushen may not start the fight when you're talking to the npc

Sha of pride after the kill the encounter continues the summoned adds are not despawnt chest to the enforcer and the portals won't summon

**Comment by cybrann** [comment]
Iron Juggernaut is not working, I removed the script until I rewrite it, as for dark shaman I just tested it and it's working perfectly.

As far as I know norushen needs to be rewritten too and I will do that later. Immerseus also needs to be rewritten. I will do fix for Sha of Pride today, but portals won't be added until Galakras, Iron Juggernaut, Dark Shamans and General Nazgrim are satisfying my standards.

**Comment by Sxzander** [comment]
i have recomplied with the last fixes and dark shamans works perfectly

**Comment by cybrann** [comment]
Try heroic mode too and give me some feedback, I didn't test it yet but I think it should work

**Comment by Sxzander** [comment]
immerseus is part and spawns his adds but are only in the Middle once again there is immerseus you can not click on and attack

**Comment by cybrann** [comment]
In 1 week Immerseus and Norushen should be rewritten and both should work properly on Normal and Heroic mode.
