### ISSUE TITLE
the fallen protector

### ISSUE THREAD

**Issue by Sxzander** [cooler-SAI/JadeCore548-patched#38]
If you brought one of the fallen protector on 1 hp they act not band of the golden lotus. If all 1 hp be they green, they are not lootbar and they remain with one in the puts to you .kill or .gm on makes. Except it has remain two debuffs Garrote and awareness as long as until it makes .kill. If you stop 5 min where one becomes vulnerable and the battle begins again with all

tested in the heroic version

**Comment by cybrann** [comment]
Please use proper English because I have not understood your report.

**Comment by Sxzander** [comment]
i have used bing translator my english is not so good

**Comment by Sxzander** [comment]
the fallen protector works good but when one of them got 1 hp then cast the boss http://www.wowhead.com/spell=143497/bond-of-the-golden-lotus that does not work.
they will be green and get full hp. If they're all dead npc to stay in the fight except it uses commands that
.GM on or .kill

**Comment by cybrann** [comment]
I see you tested this on Heroic version, problem is that some bosses are bugged on heroic. When normal mode is fully scripted I will start doing heroic mode.
