### ISSUE TITLE
Linux Debian 7 cant compile

### ISSUE THREAD

**Issue by Orangs** [cooler-SAI/JadeCore548-patched#4]
Here is complete error log
https://ctrlv.cz/shots/2016/03/30/uF58.png

**Comment by wlasser** [comment]
this is easy for fix, just ask me

**Comment by Orangs** [comment]
can u add me on skype and help me with fix? My username on skype is zalman-cze ... Thank u

**Comment by angelsss** [comment]
How to resolve , same error : can you help me ?

**Comment by wlasser** [comment]
affter testing this fix, happens shit - chat didn't work. this fix not needed for you.
