### ISSUE TITLE
Orc start quest line

### ISSUE THREAD

**Issue by alexkulya** [cooler-SAI/JadeCore548-patched#40]
Tested start quest for race Orc. All work properly, but broken the sequence of tasks.

**Comment by cybrann** [comment]
It has something to do with previous quest in chain and next quest in chain in quest template table

**Comment by alexkulya** [comment]
The fix method I know. I just want to get more precise information about the quest chains. On Wowhead there is no trust.

**Comment by alexkulya** [comment]
Make a test fix. Let's see what happens.

**Comment by alexkulya** [comment]
Solved
