### ISSUE TITLE
I am confused!

### ISSUE THREAD

**Issue by cooler-SAI** [cooler-SAI/JadeCore548-patched#48]
I am confused! why create million copyes and don't work together? it's useless and slow progress
https://github.com/JadeCore/JadeCore_5.x.x

**Comment by alexkulya** [comment]
And I do not understand this.
Тоже непонимаю этого.

**Comment by cybrann** [comment]
Let's just make private repository on bitbucket and release repack only on ac-web. Then nobody will be able to steal our work

**Comment by alexkulya** [comment]
Хорошая идея, cybrann. Принимать только людей, которые действительно хотят помочь развить проект. Cooler - босс, поэтому ему решать.
A good idea, cybrann. Accept only people who really want to help develop the project. Cooler - the boss, so for him to decide.

**Comment by cybrann** [comment]
@cooler-SAI We are waiting for your decision

**Comment by cooler-SAI** [comment]
guys, I think private project will die faster, that's why we are all here ( I am very proud have you all in my team), TrinityCore still public long time, and have many clones, but it still be TRINIITY in original, and public. many people ask me: work on my server for the money, I sad NO! coz I love what I do and my public work have respect and it'susefull ( TrinityCore have my scripts too), so, let's be stronger and  continue our public project! are you with me?

**Comment by cybrann** [comment]
I can continiue my work even if it's public but I lost my motivation because I know someone else will steal our work

**Comment by cooler-SAI** [comment]
@cybrann , he told thanks here https://github.com/JadeCore/JadeCore_5.x.x/commit/3754b556a18249e426649aed4fe7abc15e243c66

**Comment by alexkulya** [comment]
Ладно. Продолжим работу. :)
Okay. We continue the work. :)

**Comment by cooler-SAI** [comment]
@cybrann , you lost motivation?

**Comment by cybrann** [comment]
I won't stop because I'm learning coding and I need to continue and it's more fun if you have more ppl that work with you, if I lost motivation it doesn't mean I will stop helping.

**Comment by cooler-SAI** [comment]
let's  continue discuss here  https://github.com/JadeCore/JadeCore_5.x.x/issues/1

**Comment by Keital** [comment]
not that mi opinion counts but trinitycore is opensource and still there recognized by all, private source??? mmmm then you just be another private project releasing repacks. If you go private then whats the difference between you and the rest?? i'm interested in helping you guys, just studying some things, learning about the code and see what i can provide to your project. Thanks for your good work, for giving the comunity a good MOP source, for all the time dedicated and the hardwork, and lets see if i join your project in little time :D, sorry for the bad english, spanish speaker inhere

**Comment by phulo** [comment]
I'm with cooler and open source is the best solution .. Trinity never die because is free.. and many people will help with the project.
