### ISSUE TITLE
nazgrim

### ISSUE THREAD

**Issue by a7244869** [cooler-SAI/JadeCore548-patched#49]
Siege of orgrimmar BOSS  nazgrim
Rage value arrive 30, He will no a melee attack and no use any spell,until he use  HEROIC_SHOCKWAVE(143716)  Clear the rage to 0 ,  He will continue to melee attacks and use any spell

**Comment by cybrann** [comment]
I am aware of this bug but it does not happen every time so I cannot yet fix it.
