### ISSUE TITLE
can't compile

### ISSUE THREAD

**Issue by reidospalas** [cooler-SAI/JadeCore548-patched#5]
![fix](https://cloud.githubusercontent.com/assets/16887980/14517774/a03cdaea-01e7-11e6-81c5-427a2d491c8d.png)

**Comment by Mysterium** [comment]
i compiled it with VS2013: http://www.mediafire.com/download/162r2x7qrrxz11a/Debug.rar

**Comment by Orangs** [comment]
this repo is death btw...
