### ISSUE TITLE
75 warnings how to manage?

### ISSUE THREAD

**Issue by Eryck73** [cooler-SAI/JadeCore548-patched#7]
Warning	68	warning C4018: '<' : signed/unsigned mismatch	E:\Cooler\JadeCore548\src\server\scripts\Pandaria\ThroneOfThunder\boss_megaera.cpp	224	1	scripts
Warning	69	warning C4018: '<' : signed/unsigned mismatch	E:\Cooler\JadeCore548\src\server\scripts\Pandaria\ThroneOfThunder\boss_megaera.cpp	257	1	scripts
Warning	70	warning C4018: '<' : signed/unsigned mismatch	E:\Cooler\JadeCore548\src\server\scripts\Pandaria\ThroneOfThunder\boss_megaera.cpp	291	1	scripts
Warning	71	warning C4018: '<' : signed/unsigned mismatch	E:\Cooler\JadeCore548\src\server\scripts\Pandaria\ThroneOfThunder\boss_megaera.cpp	323	1	scripts
Warning	72	warning C4018: '<' : signed/unsigned mismatch	E:\Cooler\JadeCore548\src\server\scripts\Pandaria\ThroneOfThunder\boss_megaera.cpp	356	1	scripts
Warning	73	warning C4018: '<' : signed/unsigned mismatch	E:\Cooler\JadeCore548\src\server\scripts\Pandaria\ThroneOfThunder\boss_megaera.cpp	406	1	scripts
Warning	7	warning C4018: '<=' : signed/unsigned mismatch	E:\Cooler\JadeCore548\src\server\scripts\Pandaria\HeartOfFear\heart_of_fear.cpp	480	1	scripts
Warning	8	warning C4018: '<=' : signed/unsigned mismatch	E:\Cooler\JadeCore548\src\server\scripts\Pandaria\HeartOfFear\heart_of_fear.cpp	538	1	scripts
Warning	9	warning C4018: '<=' : signed/unsigned mismatch	E:\Cooler\JadeCore548\src\server\scripts\Pandaria\HeartOfFear\heart_of_fear.cpp	594	1	scripts
Warning	10	warning C4018: '<=' : signed/unsigned mismatch	E:\Cooler\JadeCore548\src\server\scripts\Pandaria\HeartOfFear\heart_of_fear.cpp	707	1	scripts
Warning	11	warning C4018: '<=' : signed/unsigned mismatch	E:\Cooler\JadeCore548\src\server\scripts\Pandaria\HeartOfFear\heart_of_fear.cpp	762	1	scripts
Warning	12	warning C4018: '<=' : signed/unsigned mismatch	E:\Cooler\JadeCore548\src\server\scripts\Pandaria\HeartOfFear\heart_of_fear.cpp	770	1	scripts
Warning	13	warning C4018: '<=' : signed/unsigned mismatch	E:\Cooler\JadeCore548\src\server\scripts\Pandaria\HeartOfFear\heart_of_fear.cpp	869	1	scripts
Warning	14	warning C4018: '<=' : signed/unsigned mismatch	E:\Cooler\JadeCore548\src\server\scripts\Pandaria\HeartOfFear\heart_of_fear.cpp	877	1	scripts
Warning	15	warning C4018: '<=' : signed/unsigned mismatch	E:\Cooler\JadeCore548\src\server\scripts\Pandaria\HeartOfFear\heart_of_fear.cpp	938	1	scripts
Warning	16	warning C4018: '<=' : signed/unsigned mismatch	E:\Cooler\JadeCore548\src\server\scripts\Pandaria\HeartOfFear\heart_of_fear.cpp	946	1	scripts
Warning	17	warning C4018: '<=' : signed/unsigned mismatch	E:\Cooler\JadeCore548\src\server\scripts\Pandaria\HeartOfFear\heart_of_fear.cpp	1150	1	scripts
Warning	18	warning C4018: '<=' : signed/unsigned mismatch	E:\Cooler\JadeCore548\src\server\scripts\Pandaria\HeartOfFear\heart_of_fear.cpp	1161	1	scripts
Warning	19	warning C4018: '<=' : signed/unsigned mismatch	E:\Cooler\JadeCore548\src\server\scripts\Pandaria\HeartOfFear\Imperial_Zorlok.cpp	847	1	scripts
Warning	20	warning C4018: '<=' : signed/unsigned mismatch	E:\Cooler\JadeCore548\src\server\scripts\Pandaria\HeartOfFear\Imperial_Zorlok.cpp	857	1	scripts
Warning	21	warning C4018: '<=' : signed/unsigned mismatch	E:\Cooler\JadeCore548\src\server\scripts\Pandaria\HeartOfFear\Imperial_Zorlok.cpp	867	1	scripts
Warning	22	warning C4018: '<=' : signed/unsigned mismatch	E:\Cooler\JadeCore548\src\server\scripts\Pandaria\HeartOfFear\Imperial_Zorlok.cpp	876	1	scripts
Warning	23	warning C4018: '<=' : signed/unsigned mismatch	E:\Cooler\JadeCore548\src\server\scripts\Pandaria\HeartOfFear\Imperial_Zorlok.cpp	886	1	scripts
Warning	24	warning C4018: '<=' : signed/unsigned mismatch	E:\Cooler\JadeCore548\src\server\scripts\Pandaria\HeartOfFear\Imperial_Zorlok.cpp	896	1	scripts
Warning	25	warning C4018: '<=' : signed/unsigned mismatch	E:\Cooler\JadeCore548\src\server\scripts\Pandaria\HeartOfFear\Imperial_Zorlok.cpp	961	1	scripts
Warning	26	warning C4018: '<=' : signed/unsigned mismatch	E:\Cooler\JadeCore548\src\server\scripts\Pandaria\HeartOfFear\Imperial_Zorlok.cpp	971	1	scripts
Warning	27	warning C4018: '<=' : signed/unsigned mismatch	E:\Cooler\JadeCore548\src\server\scripts\Pandaria\HeartOfFear\Imperial_Zorlok.cpp	981	1	scripts
Warning	28	warning C4018: '<=' : signed/unsigned mismatch	E:\Cooler\JadeCore548\src\server\scripts\Pandaria\HeartOfFear\Imperial_Zorlok.cpp	991	1	scripts
Warning	29	warning C4018: '<=' : signed/unsigned mismatch	E:\Cooler\JadeCore548\src\server\scripts\Pandaria\HeartOfFear\Blade_Lord_Tayak.cpp	662	1	scripts
Warning	30	warning C4018: '<=' : signed/unsigned mismatch	E:\Cooler\JadeCore548\src\server\scripts\Pandaria\HeartOfFear\Wind_Lord_Meljarak.cpp	1004	1	scripts
Warning	31	warning C4018: '<=' : signed/unsigned mismatch	E:\Cooler\JadeCore548\src\server\scripts\Pandaria\HeartOfFear\Wind_Lord_Meljarak.cpp	1051	1	scripts
Warning	32	warning C4018: '<=' : signed/unsigned mismatch	E:\Cooler\JadeCore548\src\server\scripts\Pandaria\HeartOfFear\Garalon.cpp	379	1	scripts
Warning	33	warning C4018: '<=' : signed/unsigned mismatch	E:\Cooler\JadeCore548\src\server\scripts\Pandaria\HeartOfFear\Garalon.cpp	537	1	scripts
Warning	34	warning C4018: '<=' : signed/unsigned mismatch	E:\Cooler\JadeCore548\src\server\scripts\Pandaria\HeartOfFear\Garalon.cpp	604	1	scripts
Warning	35	warning C4018: '<=' : signed/unsigned mismatch	E:\Cooler\JadeCore548\src\server\scripts\Pandaria\HeartOfFear\Grand_Empress_Shekzeer.cpp	221	1	scripts
Warning	36	warning C4018: '<=' : signed/unsigned mismatch	E:\Cooler\JadeCore548\src\server\scripts\Pandaria\HeartOfFear\Grand_Empress_Shekzeer.cpp	250	1	scripts
Warning	37	warning C4018: '<=' : signed/unsigned mismatch	E:\Cooler\JadeCore548\src\server\scripts\Pandaria\HeartOfFear\Grand_Empress_Shekzeer.cpp	609	1	scripts
Warning	38	warning C4018: '<=' : signed/unsigned mismatch	E:\Cooler\JadeCore548\src\server\scripts\Pandaria\HeartOfFear\Grand_Empress_Shekzeer.cpp	864	1	scripts
Warning	46	warning C4018: '<=' : signed/unsigned mismatch	E:\Cooler\JadeCore548\src\server\scripts\Pandaria\TerraceOfEndlessSpring\boss_tsulong.cpp	916	1	scripts
Warning	47	warning C4018: '<=' : signed/unsigned mismatch	E:\Cooler\JadeCore548\src\server\scripts\Pandaria\TerraceOfEndlessSpring\boss_tsulong.cpp	980	1	scripts
Warning	48	warning C4018: '<=' : signed/unsigned mismatch	E:\Cooler\JadeCore548\src\server\scripts\Pandaria\TerraceOfEndlessSpring\boss_tsulong.cpp	1051	1	scripts
Warning	49	warning C4018: '<=' : signed/unsigned mismatch	E:\Cooler\JadeCore548\src\server\scripts\Pandaria\TerraceOfEndlessSpring\boss_sha_of_fear.cpp	1212	1	scripts
Warning	53	warning C4018: '<=' : signed/unsigned mismatch	E:\Cooler\JadeCore548\src\server\scripts\Pandaria\ThroneOfThunder\boss_council.cpp	1862	1	scripts
Warning	55	warning C4018: '<=' : signed/unsigned mismatch	E:\Cooler\JadeCore548\src\server\scripts\Pandaria\ThroneOfThunder\boss_council.cpp	2060	1	scripts
Warning	56	warning C4018: '<=' : signed/unsigned mismatch	E:\Cooler\JadeCore548\src\server\scripts\Pandaria\ThroneOfThunder\boss_council.cpp	2137	1	scripts
Warning	57	warning C4018: '<=' : signed/unsigned mismatch	E:\Cooler\JadeCore548\src\server\scripts\Pandaria\ThroneOfThunder\boss_council.cpp	2184	1	scripts
Warning	58	warning C4018: '<=' : signed/unsigned mismatch	E:\Cooler\JadeCore548\src\server\scripts\Pandaria\ThroneOfThunder\boss_council.cpp	2207	1	scripts
Warning	59	warning C4018: '<=' : signed/unsigned mismatch	E:\Cooler\JadeCore548\src\server\scripts\Pandaria\ThroneOfThunder\boss_jinrokh.cpp	519	1	scripts
Warning	60	warning C4018: '<=' : signed/unsigned mismatch	E:\Cooler\JadeCore548\src\server\scripts\Pandaria\ThroneOfThunder\boss_jinrokh.cpp	533	1	scripts
Warning	61	warning C4018: '<=' : signed/unsigned mismatch	E:\Cooler\JadeCore548\src\server\scripts\Pandaria\ThroneOfThunder\boss_jinrokh.cpp	622	1	scripts
Warning	62	warning C4018: '<=' : signed/unsigned mismatch	E:\Cooler\JadeCore548\src\server\scripts\Pandaria\ThroneOfThunder\boss_jinrokh.cpp	669	1	scripts
Warning	63	warning C4018: '<=' : signed/unsigned mismatch	E:\Cooler\JadeCore548\src\server\scripts\Pandaria\ThroneOfThunder\boss_jinrokh.cpp	716	1	scripts
Warning	64	warning C4018: '<=' : signed/unsigned mismatch	E:\Cooler\JadeCore548\src\server\scripts\Pandaria\ThroneOfThunder\boss_jinrokh.cpp	916	1	scripts
Warning	65	warning C4018: '<=' : signed/unsigned mismatch	E:\Cooler\JadeCore548\src\server\scripts\Pandaria\ThroneOfThunder\boss_jinrokh.cpp	976	1	scripts
Warning	66	warning C4018: '<=' : signed/unsigned mismatch	E:\Cooler\JadeCore548\src\server\scripts\Pandaria\ThroneOfThunder\boss_jinrokh.cpp	990	1	scripts
Warning	6	warning C4060: switch statement contains no 'case' or 'default' labels	E:\Cooler\JadeCore548\src\server\game\Spells\SpellMgr.cpp	9022	1	game
Warning	43	warning C4060: switch statement contains no 'case' or 'default' labels	E:\Cooler\JadeCore548\src\server\scripts\Pandaria\SiegeNiuzaoTemple\boss_vojak.cpp	2071	1	scripts
Warning	44	warning C4060: switch statement contains no 'case' or 'default' labels	E:\Cooler\JadeCore548\src\server\scripts\Pandaria\SiegeNiuzaoTemple\boss_vojak.cpp	2114	1	scripts
Warning	45	warning C4060: switch statement contains no 'case' or 'default' labels	E:\Cooler\JadeCore548\src\server\scripts\Pandaria\SiegeNiuzaoTemple\boss_vojak.cpp	2303	1	scripts
Warning	67	warning C4060: switch statement contains no 'case' or 'default' labels	E:\Cooler\JadeCore548\src\server\scripts\Pandaria\ThroneOfThunder\boss_ji_kun.cpp	909	1	scripts
Warning	74	warning C4060: switch statement contains no 'case' or 'default' labels	E:\Cooler\JadeCore548\src\server\scripts\Pandaria\SiegeOfOrgrimmar\instance_siege_of_orgrimmar.cpp	188	1	scripts
Warning	75	warning C4065: switch statement contains 'default' but no 'case' labels	E:\Cooler\JadeCore548\src\server\scripts\Pandaria\SiegeOfOrgrimmar\boss_fallen_protectors.cpp	1627	1	scripts
Warning	50	warning C4305: '+=' : truncation from 'double' to 'float'	E:\Cooler\JadeCore548\src\server\scripts\Pandaria\ThroneOfThunder\boss_council.cpp	800	1	scripts
Warning	51	warning C4305: '+=' : truncation from 'double' to 'float'	E:\Cooler\JadeCore548\src\server\scripts\Pandaria\ThroneOfThunder\boss_council.cpp	1172	1	scripts
Warning	52	warning C4305: '+=' : truncation from 'double' to 'float'	E:\Cooler\JadeCore548\src\server\scripts\Pandaria\ThroneOfThunder\boss_council.cpp	1537	1	scripts
Warning	54	warning C4305: '+=' : truncation from 'double' to 'float'	E:\Cooler\JadeCore548\src\server\scripts\Pandaria\ThroneOfThunder\boss_council.cpp	1942	1	scripts
Warning	1	warning C4305: 'argument' : truncation from 'double' to 'float'	E:\Cooler\JadeCore548\src\server\scripts\Kalimdor\RagefireChasm\slagmaw.cpp	103	1	scripts
Warning	2	warning C4305: 'argument' : truncation from 'double' to 'float'	E:\Cooler\JadeCore548\src\server\scripts\Kalimdor\RagefireChasm\slagmaw.cpp	109	1	scripts
Warning	3	warning C4305: 'argument' : truncation from 'double' to 'float'	E:\Cooler\JadeCore548\src\server\scripts\Kalimdor\RagefireChasm\slagmaw.cpp	115	1	scripts
Warning	4	warning C4305: 'argument' : truncation from 'double' to 'float'	E:\Cooler\JadeCore548\src\server\scripts\Kalimdor\RagefireChasm\slagmaw.cpp	121	1	scripts
Warning	5	warning C4305: 'argument' : truncation from 'double' to 'float'	E:\Cooler\JadeCore548\src\server\scripts\Kalimdor\RagefireChasm\lavaguardgordoth.cpp	92	1	scripts
Warning	39	warning C4305: 'argument' : truncation from 'int' to 'uint8'	E:\Cooler\JadeCore548\src\server\scripts\Pandaria\SiegeNiuzaoTemple\boss_vojak.cpp	1813	1	scripts
Warning	41	warning C4305: 'argument' : truncation from 'int' to 'uint8'	E:\Cooler\JadeCore548\src\server\scripts\Pandaria\SiegeNiuzaoTemple\boss_vojak.cpp	1822	1	scripts
Warning	40	warning C4309: 'argument' : truncation of constant value	E:\Cooler\JadeCore548\src\server\scripts\Pandaria\SiegeNiuzaoTemple\boss_vojak.cpp	1813	1	scripts
Warning	42	warning C4309: 'argument' : truncation of constant value	E:\Cooler\JadeCore548\src\server\scripts\Pandaria\SiegeNiuzaoTemple\boss_vojak.cpp	1822	1	scripts

**Comment by cybrann** [comment]
70% of these warning are fixed - closing issue.
