### ISSUE TITLE
Crash in Heart of fear

### ISSUE THREAD

**Issue by Ramys** [cooler-SAI/JadeCore548-patched#8]
Boss Imperial_Zorlok.cpp crash  in server.
Mode Heroic 
Mode Normal!
[_worldserver.exe_[19-6_13-13-2].txt](https://github.com/cooler-SAI/JadeCore548/files/322381/_worldserver.exe_.19-6_13-13-2.txt)

**Comment by wlasser** [comment]
this log is pice of shit, guy. no one don't do anything with it. i fix many things with crashes in this core, but i don't remember what exactly. do a better debug log, with debug info (cmake with -DWITH_COREDEBUG=1) and run under debugger. I don't know how it look under windows, coz using Linux.

**Comment by cybrann** [comment]
Compile in debug mode and make new issue. This one is getting closed.
